version: '3'

volumes:
  pg_data:
  static:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: elyar1996/taski_backend
    env_file: .env
    volumes:
      - static:/static/
  frontend:
    image: elyar1996/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  gateway:
    image: elyar1996/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80